resolver: lts-16.0
packages:
- '.'
- distributed-process-tests/
extra-deps:
- git: https://github.com/haskell-distributed/network-transport-tcp.git
  commit: d87d6f55697a94a1fbf211ff9c1bb769a1e129cd
- rank1dynamic-0.4.0
- distributed-static-0.3.9
- network-transport-0.5.4
- network-transport-inmemory-0.5.2
- rematch-0.2.0.0

flags:
  distributed-process-tests:
    tcp: true
